/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GooglerpcStatus } from '../models';
// @ts-ignore
import { ProductServiceUpdateProductRequest } from '../models';
// @ts-ignore
import { V1CreateProductRequest } from '../models';
// @ts-ignore
import { V1DeleteProductReply } from '../models';
// @ts-ignore
import { V1ListProductReply } from '../models';
// @ts-ignore
import { V1ListProductRequest } from '../models';
// @ts-ignore
import { V1Product } from '../models';
/**
 * ProductServiceApi - axios parameter creator
 * @export
 */
export const ProductServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {V1CreateProductRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productServiceCreateProduct: async (body: V1CreateProductRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('productServiceCreateProduct', 'body', body)
            const localVarPath = `/v1/product`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productServiceDeleteProduct: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('productServiceDeleteProduct', 'id', id)
            const localVarPath = `/v1/product/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productServiceGetProduct: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('productServiceGetProduct', 'id', id)
            const localVarPath = `/v1/product/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [filterId$eq] 
         * @param {string} [filterId$neq] 
         * @param {string} [filterId$contains] 
         * @param {string} [filterId$startsWith] 
         * @param {string} [filterId$nstartsWith] 
         * @param {string} [filterId$endsWith] 
         * @param {string} [filterId$nendsWith] 
         * @param {Array<string>} [filterId$in] 
         * @param {Array<string>} [filterId$nin] 
         * @param {boolean} [filterId$null] 
         * @param {boolean} [filterId$nnull] 
         * @param {boolean} [filterId$empty] 
         * @param {boolean} [filterId$nempty] 
         * @param {string} [filterId$like] 
         * @param {string} [filterName$eq] 
         * @param {string} [filterName$neq] 
         * @param {string} [filterName$contains] 
         * @param {string} [filterName$startsWith] 
         * @param {string} [filterName$nstartsWith] 
         * @param {string} [filterName$endsWith] 
         * @param {string} [filterName$nendsWith] 
         * @param {Array<string>} [filterName$in] 
         * @param {Array<string>} [filterName$nin] 
         * @param {boolean} [filterName$null] 
         * @param {boolean} [filterName$nnull] 
         * @param {boolean} [filterName$empty] 
         * @param {boolean} [filterName$nempty] 
         * @param {string} [filterName$like] 
         * @param {boolean} [filterInternal$eq] 
         * @param {boolean} [filterInternal$neq] 
         * @param {boolean} [filterInternal$null] 
         * @param {boolean} [filterInternal$nnull] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productServiceListProduct: async (pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, filterId$eq?: string, filterId$neq?: string, filterId$contains?: string, filterId$startsWith?: string, filterId$nstartsWith?: string, filterId$endsWith?: string, filterId$nendsWith?: string, filterId$in?: Array<string>, filterId$nin?: Array<string>, filterId$null?: boolean, filterId$nnull?: boolean, filterId$empty?: boolean, filterId$nempty?: boolean, filterId$like?: string, filterName$eq?: string, filterName$neq?: string, filterName$contains?: string, filterName$startsWith?: string, filterName$nstartsWith?: string, filterName$endsWith?: string, filterName$nendsWith?: string, filterName$in?: Array<string>, filterName$nin?: Array<string>, filterName$null?: boolean, filterName$nnull?: boolean, filterName$empty?: boolean, filterName$nempty?: boolean, filterName$like?: string, filterInternal$eq?: boolean, filterInternal$neq?: boolean, filterInternal$null?: boolean, filterInternal$nnull?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/product`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (pageOffset !== undefined) {
                localVarQueryParameter['pageOffset'] = pageOffset;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }

            if (fields !== undefined) {
                localVarQueryParameter['fields'] = fields;
            }

            if (filterId$eq !== undefined) {
                localVarQueryParameter['filter.id.$eq'] = filterId$eq;
            }

            if (filterId$neq !== undefined) {
                localVarQueryParameter['filter.id.$neq'] = filterId$neq;
            }

            if (filterId$contains !== undefined) {
                localVarQueryParameter['filter.id.$contains'] = filterId$contains;
            }

            if (filterId$startsWith !== undefined) {
                localVarQueryParameter['filter.id.$starts_with'] = filterId$startsWith;
            }

            if (filterId$nstartsWith !== undefined) {
                localVarQueryParameter['filter.id.$nstarts_with'] = filterId$nstartsWith;
            }

            if (filterId$endsWith !== undefined) {
                localVarQueryParameter['filter.id.$ends_with'] = filterId$endsWith;
            }

            if (filterId$nendsWith !== undefined) {
                localVarQueryParameter['filter.id.$nends_with'] = filterId$nendsWith;
            }

            if (filterId$in) {
                localVarQueryParameter['filter.id.$in'] = filterId$in;
            }

            if (filterId$nin) {
                localVarQueryParameter['filter.id.$nin'] = filterId$nin;
            }

            if (filterId$null !== undefined) {
                localVarQueryParameter['filter.id.$null'] = filterId$null;
            }

            if (filterId$nnull !== undefined) {
                localVarQueryParameter['filter.id.$nnull'] = filterId$nnull;
            }

            if (filterId$empty !== undefined) {
                localVarQueryParameter['filter.id.$empty'] = filterId$empty;
            }

            if (filterId$nempty !== undefined) {
                localVarQueryParameter['filter.id.$nempty'] = filterId$nempty;
            }

            if (filterId$like !== undefined) {
                localVarQueryParameter['filter.id.$like'] = filterId$like;
            }

            if (filterName$eq !== undefined) {
                localVarQueryParameter['filter.name.$eq'] = filterName$eq;
            }

            if (filterName$neq !== undefined) {
                localVarQueryParameter['filter.name.$neq'] = filterName$neq;
            }

            if (filterName$contains !== undefined) {
                localVarQueryParameter['filter.name.$contains'] = filterName$contains;
            }

            if (filterName$startsWith !== undefined) {
                localVarQueryParameter['filter.name.$starts_with'] = filterName$startsWith;
            }

            if (filterName$nstartsWith !== undefined) {
                localVarQueryParameter['filter.name.$nstarts_with'] = filterName$nstartsWith;
            }

            if (filterName$endsWith !== undefined) {
                localVarQueryParameter['filter.name.$ends_with'] = filterName$endsWith;
            }

            if (filterName$nendsWith !== undefined) {
                localVarQueryParameter['filter.name.$nends_with'] = filterName$nendsWith;
            }

            if (filterName$in) {
                localVarQueryParameter['filter.name.$in'] = filterName$in;
            }

            if (filterName$nin) {
                localVarQueryParameter['filter.name.$nin'] = filterName$nin;
            }

            if (filterName$null !== undefined) {
                localVarQueryParameter['filter.name.$null'] = filterName$null;
            }

            if (filterName$nnull !== undefined) {
                localVarQueryParameter['filter.name.$nnull'] = filterName$nnull;
            }

            if (filterName$empty !== undefined) {
                localVarQueryParameter['filter.name.$empty'] = filterName$empty;
            }

            if (filterName$nempty !== undefined) {
                localVarQueryParameter['filter.name.$nempty'] = filterName$nempty;
            }

            if (filterName$like !== undefined) {
                localVarQueryParameter['filter.name.$like'] = filterName$like;
            }

            if (filterInternal$eq !== undefined) {
                localVarQueryParameter['filter.internal.$eq'] = filterInternal$eq;
            }

            if (filterInternal$neq !== undefined) {
                localVarQueryParameter['filter.internal.$neq'] = filterInternal$neq;
            }

            if (filterInternal$null !== undefined) {
                localVarQueryParameter['filter.internal.$null'] = filterInternal$null;
            }

            if (filterInternal$nnull !== undefined) {
                localVarQueryParameter['filter.internal.$nnull'] = filterInternal$nnull;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {V1ListProductRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productServiceListProduct2: async (body: V1ListProductRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('productServiceListProduct2', 'body', body)
            const localVarPath = `/v1/product/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {ProductServiceUpdateProductRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productServiceUpdateProduct: async (productId: string, body: ProductServiceUpdateProductRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('productServiceUpdateProduct', 'productId', productId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('productServiceUpdateProduct', 'body', body)
            const localVarPath = `/v1/product/{product.id}`
                .replace(`{${"product.id"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} productId 
         * @param {ProductServiceUpdateProductRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productServiceUpdateProduct2: async (productId: string, body: ProductServiceUpdateProductRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('productServiceUpdateProduct2', 'productId', productId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('productServiceUpdateProduct2', 'body', body)
            const localVarPath = `/v1/product/{product.id}`
                .replace(`{${"product.id"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProductServiceApi - functional programming interface
 * @export
 */
export const ProductServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProductServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {V1CreateProductRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productServiceCreateProduct(body: V1CreateProductRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Product>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productServiceCreateProduct(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productServiceDeleteProduct(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1DeleteProductReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productServiceDeleteProduct(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productServiceGetProduct(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Product>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productServiceGetProduct(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [filterId$eq] 
         * @param {string} [filterId$neq] 
         * @param {string} [filterId$contains] 
         * @param {string} [filterId$startsWith] 
         * @param {string} [filterId$nstartsWith] 
         * @param {string} [filterId$endsWith] 
         * @param {string} [filterId$nendsWith] 
         * @param {Array<string>} [filterId$in] 
         * @param {Array<string>} [filterId$nin] 
         * @param {boolean} [filterId$null] 
         * @param {boolean} [filterId$nnull] 
         * @param {boolean} [filterId$empty] 
         * @param {boolean} [filterId$nempty] 
         * @param {string} [filterId$like] 
         * @param {string} [filterName$eq] 
         * @param {string} [filterName$neq] 
         * @param {string} [filterName$contains] 
         * @param {string} [filterName$startsWith] 
         * @param {string} [filterName$nstartsWith] 
         * @param {string} [filterName$endsWith] 
         * @param {string} [filterName$nendsWith] 
         * @param {Array<string>} [filterName$in] 
         * @param {Array<string>} [filterName$nin] 
         * @param {boolean} [filterName$null] 
         * @param {boolean} [filterName$nnull] 
         * @param {boolean} [filterName$empty] 
         * @param {boolean} [filterName$nempty] 
         * @param {string} [filterName$like] 
         * @param {boolean} [filterInternal$eq] 
         * @param {boolean} [filterInternal$neq] 
         * @param {boolean} [filterInternal$null] 
         * @param {boolean} [filterInternal$nnull] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productServiceListProduct(pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, filterId$eq?: string, filterId$neq?: string, filterId$contains?: string, filterId$startsWith?: string, filterId$nstartsWith?: string, filterId$endsWith?: string, filterId$nendsWith?: string, filterId$in?: Array<string>, filterId$nin?: Array<string>, filterId$null?: boolean, filterId$nnull?: boolean, filterId$empty?: boolean, filterId$nempty?: boolean, filterId$like?: string, filterName$eq?: string, filterName$neq?: string, filterName$contains?: string, filterName$startsWith?: string, filterName$nstartsWith?: string, filterName$endsWith?: string, filterName$nendsWith?: string, filterName$in?: Array<string>, filterName$nin?: Array<string>, filterName$null?: boolean, filterName$nnull?: boolean, filterName$empty?: boolean, filterName$nempty?: boolean, filterName$like?: string, filterInternal$eq?: boolean, filterInternal$neq?: boolean, filterInternal$null?: boolean, filterInternal$nnull?: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1ListProductReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productServiceListProduct(pageOffset, pageSize, search, sort, fields, filterId$eq, filterId$neq, filterId$contains, filterId$startsWith, filterId$nstartsWith, filterId$endsWith, filterId$nendsWith, filterId$in, filterId$nin, filterId$null, filterId$nnull, filterId$empty, filterId$nempty, filterId$like, filterName$eq, filterName$neq, filterName$contains, filterName$startsWith, filterName$nstartsWith, filterName$endsWith, filterName$nendsWith, filterName$in, filterName$nin, filterName$null, filterName$nnull, filterName$empty, filterName$nempty, filterName$like, filterInternal$eq, filterInternal$neq, filterInternal$null, filterInternal$nnull, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {V1ListProductRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productServiceListProduct2(body: V1ListProductRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1ListProductReply>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productServiceListProduct2(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} productId 
         * @param {ProductServiceUpdateProductRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productServiceUpdateProduct(productId: string, body: ProductServiceUpdateProductRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Product>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productServiceUpdateProduct(productId, body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} productId 
         * @param {ProductServiceUpdateProductRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productServiceUpdateProduct2(productId: string, body: ProductServiceUpdateProductRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Product>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productServiceUpdateProduct2(productId, body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ProductServiceApi - factory interface
 * @export
 */
export const ProductServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProductServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {ProductServiceApiProductServiceCreateProductRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productServiceCreateProduct(requestParameters: ProductServiceApiProductServiceCreateProductRequest, options?: AxiosRequestConfig): AxiosPromise<V1Product> {
            return localVarFp.productServiceCreateProduct(requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProductServiceApiProductServiceDeleteProductRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productServiceDeleteProduct(requestParameters: ProductServiceApiProductServiceDeleteProductRequest, options?: AxiosRequestConfig): AxiosPromise<V1DeleteProductReply> {
            return localVarFp.productServiceDeleteProduct(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProductServiceApiProductServiceGetProductRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productServiceGetProduct(requestParameters: ProductServiceApiProductServiceGetProductRequest, options?: AxiosRequestConfig): AxiosPromise<V1Product> {
            return localVarFp.productServiceGetProduct(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProductServiceApiProductServiceListProductRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productServiceListProduct(requestParameters: ProductServiceApiProductServiceListProductRequest = {}, options?: AxiosRequestConfig): AxiosPromise<V1ListProductReply> {
            return localVarFp.productServiceListProduct(requestParameters.pageOffset, requestParameters.pageSize, requestParameters.search, requestParameters.sort, requestParameters.fields, requestParameters.filterId$eq, requestParameters.filterId$neq, requestParameters.filterId$contains, requestParameters.filterId$startsWith, requestParameters.filterId$nstartsWith, requestParameters.filterId$endsWith, requestParameters.filterId$nendsWith, requestParameters.filterId$in, requestParameters.filterId$nin, requestParameters.filterId$null, requestParameters.filterId$nnull, requestParameters.filterId$empty, requestParameters.filterId$nempty, requestParameters.filterId$like, requestParameters.filterName$eq, requestParameters.filterName$neq, requestParameters.filterName$contains, requestParameters.filterName$startsWith, requestParameters.filterName$nstartsWith, requestParameters.filterName$endsWith, requestParameters.filterName$nendsWith, requestParameters.filterName$in, requestParameters.filterName$nin, requestParameters.filterName$null, requestParameters.filterName$nnull, requestParameters.filterName$empty, requestParameters.filterName$nempty, requestParameters.filterName$like, requestParameters.filterInternal$eq, requestParameters.filterInternal$neq, requestParameters.filterInternal$null, requestParameters.filterInternal$nnull, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProductServiceApiProductServiceListProduct2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productServiceListProduct2(requestParameters: ProductServiceApiProductServiceListProduct2Request, options?: AxiosRequestConfig): AxiosPromise<V1ListProductReply> {
            return localVarFp.productServiceListProduct2(requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProductServiceApiProductServiceUpdateProductRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productServiceUpdateProduct(requestParameters: ProductServiceApiProductServiceUpdateProductRequest, options?: AxiosRequestConfig): AxiosPromise<V1Product> {
            return localVarFp.productServiceUpdateProduct(requestParameters.productId, requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ProductServiceApiProductServiceUpdateProduct2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productServiceUpdateProduct2(requestParameters: ProductServiceApiProductServiceUpdateProduct2Request, options?: AxiosRequestConfig): AxiosPromise<V1Product> {
            return localVarFp.productServiceUpdateProduct2(requestParameters.productId, requestParameters.body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for productServiceCreateProduct operation in ProductServiceApi.
 * @export
 * @interface ProductServiceApiProductServiceCreateProductRequest
 */
export interface ProductServiceApiProductServiceCreateProductRequest {
    /**
     * 
     * @type {V1CreateProductRequest}
     * @memberof ProductServiceApiProductServiceCreateProduct
     */
    readonly body: V1CreateProductRequest
}

/**
 * Request parameters for productServiceDeleteProduct operation in ProductServiceApi.
 * @export
 * @interface ProductServiceApiProductServiceDeleteProductRequest
 */
export interface ProductServiceApiProductServiceDeleteProductRequest {
    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceDeleteProduct
     */
    readonly id: string
}

/**
 * Request parameters for productServiceGetProduct operation in ProductServiceApi.
 * @export
 * @interface ProductServiceApiProductServiceGetProductRequest
 */
export interface ProductServiceApiProductServiceGetProductRequest {
    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceGetProduct
     */
    readonly id: string
}

/**
 * Request parameters for productServiceListProduct operation in ProductServiceApi.
 * @export
 * @interface ProductServiceApiProductServiceListProductRequest
 */
export interface ProductServiceApiProductServiceListProductRequest {
    /**
     * 
     * @type {number}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly pageOffset?: number

    /**
     * 
     * @type {number}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly pageSize?: number

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly search?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly sort?: Array<string>

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly fields?: string

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterId$eq?: string

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterId$neq?: string

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterId$contains?: string

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterId$startsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterId$nstartsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterId$endsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterId$nendsWith?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterId$in?: Array<string>

    /**
     * 
     * @type {Array<string>}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterId$nin?: Array<string>

    /**
     * 
     * @type {boolean}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterId$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterId$nnull?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterId$empty?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterId$nempty?: boolean

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterId$like?: string

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterName$eq?: string

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterName$neq?: string

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterName$contains?: string

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterName$startsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterName$nstartsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterName$endsWith?: string

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterName$nendsWith?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterName$in?: Array<string>

    /**
     * 
     * @type {Array<string>}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterName$nin?: Array<string>

    /**
     * 
     * @type {boolean}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterName$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterName$nnull?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterName$empty?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterName$nempty?: boolean

    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterName$like?: string

    /**
     * 
     * @type {boolean}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterInternal$eq?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterInternal$neq?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterInternal$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof ProductServiceApiProductServiceListProduct
     */
    readonly filterInternal$nnull?: boolean
}

/**
 * Request parameters for productServiceListProduct2 operation in ProductServiceApi.
 * @export
 * @interface ProductServiceApiProductServiceListProduct2Request
 */
export interface ProductServiceApiProductServiceListProduct2Request {
    /**
     * 
     * @type {V1ListProductRequest}
     * @memberof ProductServiceApiProductServiceListProduct2
     */
    readonly body: V1ListProductRequest
}

/**
 * Request parameters for productServiceUpdateProduct operation in ProductServiceApi.
 * @export
 * @interface ProductServiceApiProductServiceUpdateProductRequest
 */
export interface ProductServiceApiProductServiceUpdateProductRequest {
    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceUpdateProduct
     */
    readonly productId: string

    /**
     * 
     * @type {ProductServiceUpdateProductRequest}
     * @memberof ProductServiceApiProductServiceUpdateProduct
     */
    readonly body: ProductServiceUpdateProductRequest
}

/**
 * Request parameters for productServiceUpdateProduct2 operation in ProductServiceApi.
 * @export
 * @interface ProductServiceApiProductServiceUpdateProduct2Request
 */
export interface ProductServiceApiProductServiceUpdateProduct2Request {
    /**
     * 
     * @type {string}
     * @memberof ProductServiceApiProductServiceUpdateProduct2
     */
    readonly productId: string

    /**
     * 
     * @type {ProductServiceUpdateProductRequest}
     * @memberof ProductServiceApiProductServiceUpdateProduct2
     */
    readonly body: ProductServiceUpdateProductRequest
}

/**
 * ProductServiceApi - object-oriented interface
 * @export
 * @class ProductServiceApi
 * @extends {BaseAPI}
 */
export class ProductServiceApi extends BaseAPI {
    /**
     * 
     * @param {ProductServiceApiProductServiceCreateProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductServiceApi
     */
    public productServiceCreateProduct(requestParameters: ProductServiceApiProductServiceCreateProductRequest, options?: AxiosRequestConfig) {
        return ProductServiceApiFp(this.configuration).productServiceCreateProduct(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProductServiceApiProductServiceDeleteProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductServiceApi
     */
    public productServiceDeleteProduct(requestParameters: ProductServiceApiProductServiceDeleteProductRequest, options?: AxiosRequestConfig) {
        return ProductServiceApiFp(this.configuration).productServiceDeleteProduct(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProductServiceApiProductServiceGetProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductServiceApi
     */
    public productServiceGetProduct(requestParameters: ProductServiceApiProductServiceGetProductRequest, options?: AxiosRequestConfig) {
        return ProductServiceApiFp(this.configuration).productServiceGetProduct(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProductServiceApiProductServiceListProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductServiceApi
     */
    public productServiceListProduct(requestParameters: ProductServiceApiProductServiceListProductRequest = {}, options?: AxiosRequestConfig) {
        return ProductServiceApiFp(this.configuration).productServiceListProduct(requestParameters.pageOffset, requestParameters.pageSize, requestParameters.search, requestParameters.sort, requestParameters.fields, requestParameters.filterId$eq, requestParameters.filterId$neq, requestParameters.filterId$contains, requestParameters.filterId$startsWith, requestParameters.filterId$nstartsWith, requestParameters.filterId$endsWith, requestParameters.filterId$nendsWith, requestParameters.filterId$in, requestParameters.filterId$nin, requestParameters.filterId$null, requestParameters.filterId$nnull, requestParameters.filterId$empty, requestParameters.filterId$nempty, requestParameters.filterId$like, requestParameters.filterName$eq, requestParameters.filterName$neq, requestParameters.filterName$contains, requestParameters.filterName$startsWith, requestParameters.filterName$nstartsWith, requestParameters.filterName$endsWith, requestParameters.filterName$nendsWith, requestParameters.filterName$in, requestParameters.filterName$nin, requestParameters.filterName$null, requestParameters.filterName$nnull, requestParameters.filterName$empty, requestParameters.filterName$nempty, requestParameters.filterName$like, requestParameters.filterInternal$eq, requestParameters.filterInternal$neq, requestParameters.filterInternal$null, requestParameters.filterInternal$nnull, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProductServiceApiProductServiceListProduct2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductServiceApi
     */
    public productServiceListProduct2(requestParameters: ProductServiceApiProductServiceListProduct2Request, options?: AxiosRequestConfig) {
        return ProductServiceApiFp(this.configuration).productServiceListProduct2(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProductServiceApiProductServiceUpdateProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductServiceApi
     */
    public productServiceUpdateProduct(requestParameters: ProductServiceApiProductServiceUpdateProductRequest, options?: AxiosRequestConfig) {
        return ProductServiceApiFp(this.configuration).productServiceUpdateProduct(requestParameters.productId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ProductServiceApiProductServiceUpdateProduct2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductServiceApi
     */
    public productServiceUpdateProduct2(requestParameters: ProductServiceApiProductServiceUpdateProduct2Request, options?: AxiosRequestConfig) {
        return ProductServiceApiFp(this.configuration).productServiceUpdateProduct2(requestParameters.productId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}

