/* tslint:disable */
/* eslint-disable */
/**
 * Realtime Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GooglerpcStatus } from '../models';
// @ts-ignore
import { RoleServiceUpdateRolePermissionRequest } from '../models';
// @ts-ignore
import { RoleServiceUpdateRoleRequest } from '../models';
// @ts-ignore
import { V1CreateRoleRequest } from '../models';
// @ts-ignore
import { V1GetRolePermissionResponse } from '../models';
// @ts-ignore
import { V1ListRolesRequest } from '../models';
// @ts-ignore
import { V1ListRolesResponse } from '../models';
// @ts-ignore
import { V1Role } from '../models';
/**
 * RoleServiceApi - axios parameter creator
 * @export
 */
export const RoleServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary authz: user.role,*,create
         * @param {V1CreateRoleRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceCreateRole: async (body: V1CreateRoleRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('roleServiceCreateRole', 'body', body)
            const localVarPath = `/v1/role`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary authz: user.role,id,delete
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceDeleteRole: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('roleServiceDeleteRole', 'id', id)
            const localVarPath = `/v1/role/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary authz: user.role,id,get
         * @param {string} id id or name should be provided
         * @param {string} [name] id or name should be provided
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceGetRole: async (id: string, name?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('roleServiceGetRole', 'id', id)
            const localVarPath = `/v1/role/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceGetRolePermission: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('roleServiceGetRolePermission', 'id', id)
            const localVarPath = `/v1/role/{id}/permission`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary authz: user.role,*,list
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [filterId$eq] 
         * @param {string} [filterId$neq] 
         * @param {string} [filterId$contains] 
         * @param {string} [filterId$startsWith] 
         * @param {string} [filterId$nstartsWith] 
         * @param {string} [filterId$endsWith] 
         * @param {string} [filterId$nendsWith] 
         * @param {Array<string>} [filterId$in] 
         * @param {Array<string>} [filterId$nin] 
         * @param {boolean} [filterId$null] 
         * @param {boolean} [filterId$nnull] 
         * @param {boolean} [filterId$empty] 
         * @param {boolean} [filterId$nempty] 
         * @param {string} [filterId$like] 
         * @param {string} [filterName$eq] 
         * @param {string} [filterName$neq] 
         * @param {string} [filterName$contains] 
         * @param {string} [filterName$startsWith] 
         * @param {string} [filterName$nstartsWith] 
         * @param {string} [filterName$endsWith] 
         * @param {string} [filterName$nendsWith] 
         * @param {Array<string>} [filterName$in] 
         * @param {Array<string>} [filterName$nin] 
         * @param {boolean} [filterName$null] 
         * @param {boolean} [filterName$nnull] 
         * @param {boolean} [filterName$empty] 
         * @param {boolean} [filterName$nempty] 
         * @param {string} [filterName$like] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceListRoles: async (pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, filterId$eq?: string, filterId$neq?: string, filterId$contains?: string, filterId$startsWith?: string, filterId$nstartsWith?: string, filterId$endsWith?: string, filterId$nendsWith?: string, filterId$in?: Array<string>, filterId$nin?: Array<string>, filterId$null?: boolean, filterId$nnull?: boolean, filterId$empty?: boolean, filterId$nempty?: boolean, filterId$like?: string, filterName$eq?: string, filterName$neq?: string, filterName$contains?: string, filterName$startsWith?: string, filterName$nstartsWith?: string, filterName$endsWith?: string, filterName$nendsWith?: string, filterName$in?: Array<string>, filterName$nin?: Array<string>, filterName$null?: boolean, filterName$nnull?: boolean, filterName$empty?: boolean, filterName$nempty?: boolean, filterName$like?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/roles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (pageOffset !== undefined) {
                localVarQueryParameter['pageOffset'] = pageOffset;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }

            if (fields !== undefined) {
                localVarQueryParameter['fields'] = fields;
            }

            if (filterId$eq !== undefined) {
                localVarQueryParameter['filter.id.$eq'] = filterId$eq;
            }

            if (filterId$neq !== undefined) {
                localVarQueryParameter['filter.id.$neq'] = filterId$neq;
            }

            if (filterId$contains !== undefined) {
                localVarQueryParameter['filter.id.$contains'] = filterId$contains;
            }

            if (filterId$startsWith !== undefined) {
                localVarQueryParameter['filter.id.$starts_with'] = filterId$startsWith;
            }

            if (filterId$nstartsWith !== undefined) {
                localVarQueryParameter['filter.id.$nstarts_with'] = filterId$nstartsWith;
            }

            if (filterId$endsWith !== undefined) {
                localVarQueryParameter['filter.id.$ends_with'] = filterId$endsWith;
            }

            if (filterId$nendsWith !== undefined) {
                localVarQueryParameter['filter.id.$nends_with'] = filterId$nendsWith;
            }

            if (filterId$in) {
                localVarQueryParameter['filter.id.$in'] = filterId$in;
            }

            if (filterId$nin) {
                localVarQueryParameter['filter.id.$nin'] = filterId$nin;
            }

            if (filterId$null !== undefined) {
                localVarQueryParameter['filter.id.$null'] = filterId$null;
            }

            if (filterId$nnull !== undefined) {
                localVarQueryParameter['filter.id.$nnull'] = filterId$nnull;
            }

            if (filterId$empty !== undefined) {
                localVarQueryParameter['filter.id.$empty'] = filterId$empty;
            }

            if (filterId$nempty !== undefined) {
                localVarQueryParameter['filter.id.$nempty'] = filterId$nempty;
            }

            if (filterId$like !== undefined) {
                localVarQueryParameter['filter.id.$like'] = filterId$like;
            }

            if (filterName$eq !== undefined) {
                localVarQueryParameter['filter.name.$eq'] = filterName$eq;
            }

            if (filterName$neq !== undefined) {
                localVarQueryParameter['filter.name.$neq'] = filterName$neq;
            }

            if (filterName$contains !== undefined) {
                localVarQueryParameter['filter.name.$contains'] = filterName$contains;
            }

            if (filterName$startsWith !== undefined) {
                localVarQueryParameter['filter.name.$starts_with'] = filterName$startsWith;
            }

            if (filterName$nstartsWith !== undefined) {
                localVarQueryParameter['filter.name.$nstarts_with'] = filterName$nstartsWith;
            }

            if (filterName$endsWith !== undefined) {
                localVarQueryParameter['filter.name.$ends_with'] = filterName$endsWith;
            }

            if (filterName$nendsWith !== undefined) {
                localVarQueryParameter['filter.name.$nends_with'] = filterName$nendsWith;
            }

            if (filterName$in) {
                localVarQueryParameter['filter.name.$in'] = filterName$in;
            }

            if (filterName$nin) {
                localVarQueryParameter['filter.name.$nin'] = filterName$nin;
            }

            if (filterName$null !== undefined) {
                localVarQueryParameter['filter.name.$null'] = filterName$null;
            }

            if (filterName$nnull !== undefined) {
                localVarQueryParameter['filter.name.$nnull'] = filterName$nnull;
            }

            if (filterName$empty !== undefined) {
                localVarQueryParameter['filter.name.$empty'] = filterName$empty;
            }

            if (filterName$nempty !== undefined) {
                localVarQueryParameter['filter.name.$nempty'] = filterName$nempty;
            }

            if (filterName$like !== undefined) {
                localVarQueryParameter['filter.name.$like'] = filterName$like;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary authz: user.role,*,list
         * @param {V1ListRolesRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceListRoles2: async (body: V1ListRolesRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('roleServiceListRoles2', 'body', body)
            const localVarPath = `/v1/role/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary authz: user.role,id,update
         * @param {string} roleId 
         * @param {RoleServiceUpdateRoleRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceUpdateRole: async (roleId: string, body: RoleServiceUpdateRoleRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roleId' is not null or undefined
            assertParamExists('roleServiceUpdateRole', 'roleId', roleId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('roleServiceUpdateRole', 'body', body)
            const localVarPath = `/v1/role/{role.id}`
                .replace(`{${"role.id"}}`, encodeURIComponent(String(roleId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary authz: user.role,id,update
         * @param {string} roleId 
         * @param {RoleServiceUpdateRoleRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceUpdateRole2: async (roleId: string, body: RoleServiceUpdateRoleRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roleId' is not null or undefined
            assertParamExists('roleServiceUpdateRole2', 'roleId', roleId)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('roleServiceUpdateRole2', 'body', body)
            const localVarPath = `/v1/role/{role.id}`
                .replace(`{${"role.id"}}`, encodeURIComponent(String(roleId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {RoleServiceUpdateRolePermissionRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceUpdateRolePermission: async (id: string, body: RoleServiceUpdateRolePermissionRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('roleServiceUpdateRolePermission', 'id', id)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('roleServiceUpdateRolePermission', 'body', body)
            const localVarPath = `/v1/role/{id}/permission`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RoleServiceApi - functional programming interface
 * @export
 */
export const RoleServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RoleServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary authz: user.role,*,create
         * @param {V1CreateRoleRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async roleServiceCreateRole(body: V1CreateRoleRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Role>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.roleServiceCreateRole(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary authz: user.role,id,delete
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async roleServiceDeleteRole(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.roleServiceDeleteRole(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary authz: user.role,id,get
         * @param {string} id id or name should be provided
         * @param {string} [name] id or name should be provided
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async roleServiceGetRole(id: string, name?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Role>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.roleServiceGetRole(id, name, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async roleServiceGetRolePermission(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1GetRolePermissionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.roleServiceGetRolePermission(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary authz: user.role,*,list
         * @param {number} [pageOffset] 
         * @param {number} [pageSize] 
         * @param {string} [search] 
         * @param {Array<string>} [sort] 
         * @param {string} [fields] 
         * @param {string} [filterId$eq] 
         * @param {string} [filterId$neq] 
         * @param {string} [filterId$contains] 
         * @param {string} [filterId$startsWith] 
         * @param {string} [filterId$nstartsWith] 
         * @param {string} [filterId$endsWith] 
         * @param {string} [filterId$nendsWith] 
         * @param {Array<string>} [filterId$in] 
         * @param {Array<string>} [filterId$nin] 
         * @param {boolean} [filterId$null] 
         * @param {boolean} [filterId$nnull] 
         * @param {boolean} [filterId$empty] 
         * @param {boolean} [filterId$nempty] 
         * @param {string} [filterId$like] 
         * @param {string} [filterName$eq] 
         * @param {string} [filterName$neq] 
         * @param {string} [filterName$contains] 
         * @param {string} [filterName$startsWith] 
         * @param {string} [filterName$nstartsWith] 
         * @param {string} [filterName$endsWith] 
         * @param {string} [filterName$nendsWith] 
         * @param {Array<string>} [filterName$in] 
         * @param {Array<string>} [filterName$nin] 
         * @param {boolean} [filterName$null] 
         * @param {boolean} [filterName$nnull] 
         * @param {boolean} [filterName$empty] 
         * @param {boolean} [filterName$nempty] 
         * @param {string} [filterName$like] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async roleServiceListRoles(pageOffset?: number, pageSize?: number, search?: string, sort?: Array<string>, fields?: string, filterId$eq?: string, filterId$neq?: string, filterId$contains?: string, filterId$startsWith?: string, filterId$nstartsWith?: string, filterId$endsWith?: string, filterId$nendsWith?: string, filterId$in?: Array<string>, filterId$nin?: Array<string>, filterId$null?: boolean, filterId$nnull?: boolean, filterId$empty?: boolean, filterId$nempty?: boolean, filterId$like?: string, filterName$eq?: string, filterName$neq?: string, filterName$contains?: string, filterName$startsWith?: string, filterName$nstartsWith?: string, filterName$endsWith?: string, filterName$nendsWith?: string, filterName$in?: Array<string>, filterName$nin?: Array<string>, filterName$null?: boolean, filterName$nnull?: boolean, filterName$empty?: boolean, filterName$nempty?: boolean, filterName$like?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1ListRolesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.roleServiceListRoles(pageOffset, pageSize, search, sort, fields, filterId$eq, filterId$neq, filterId$contains, filterId$startsWith, filterId$nstartsWith, filterId$endsWith, filterId$nendsWith, filterId$in, filterId$nin, filterId$null, filterId$nnull, filterId$empty, filterId$nempty, filterId$like, filterName$eq, filterName$neq, filterName$contains, filterName$startsWith, filterName$nstartsWith, filterName$endsWith, filterName$nendsWith, filterName$in, filterName$nin, filterName$null, filterName$nnull, filterName$empty, filterName$nempty, filterName$like, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary authz: user.role,*,list
         * @param {V1ListRolesRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async roleServiceListRoles2(body: V1ListRolesRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1ListRolesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.roleServiceListRoles2(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary authz: user.role,id,update
         * @param {string} roleId 
         * @param {RoleServiceUpdateRoleRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async roleServiceUpdateRole(roleId: string, body: RoleServiceUpdateRoleRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Role>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.roleServiceUpdateRole(roleId, body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary authz: user.role,id,update
         * @param {string} roleId 
         * @param {RoleServiceUpdateRoleRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async roleServiceUpdateRole2(roleId: string, body: RoleServiceUpdateRoleRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1Role>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.roleServiceUpdateRole2(roleId, body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {RoleServiceUpdateRolePermissionRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async roleServiceUpdateRolePermission(id: string, body: RoleServiceUpdateRolePermissionRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.roleServiceUpdateRolePermission(id, body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RoleServiceApi - factory interface
 * @export
 */
export const RoleServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RoleServiceApiFp(configuration)
    return {
        /**
         * 
         * @summary authz: user.role,*,create
         * @param {RoleServiceApiRoleServiceCreateRoleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceCreateRole(requestParameters: RoleServiceApiRoleServiceCreateRoleRequest, options?: AxiosRequestConfig): AxiosPromise<V1Role> {
            return localVarFp.roleServiceCreateRole(requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary authz: user.role,id,delete
         * @param {RoleServiceApiRoleServiceDeleteRoleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceDeleteRole(requestParameters: RoleServiceApiRoleServiceDeleteRoleRequest, options?: AxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.roleServiceDeleteRole(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary authz: user.role,id,get
         * @param {RoleServiceApiRoleServiceGetRoleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceGetRole(requestParameters: RoleServiceApiRoleServiceGetRoleRequest, options?: AxiosRequestConfig): AxiosPromise<V1Role> {
            return localVarFp.roleServiceGetRole(requestParameters.id, requestParameters.name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RoleServiceApiRoleServiceGetRolePermissionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceGetRolePermission(requestParameters: RoleServiceApiRoleServiceGetRolePermissionRequest, options?: AxiosRequestConfig): AxiosPromise<V1GetRolePermissionResponse> {
            return localVarFp.roleServiceGetRolePermission(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary authz: user.role,*,list
         * @param {RoleServiceApiRoleServiceListRolesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceListRoles(requestParameters: RoleServiceApiRoleServiceListRolesRequest = {}, options?: AxiosRequestConfig): AxiosPromise<V1ListRolesResponse> {
            return localVarFp.roleServiceListRoles(requestParameters.pageOffset, requestParameters.pageSize, requestParameters.search, requestParameters.sort, requestParameters.fields, requestParameters.filterId$eq, requestParameters.filterId$neq, requestParameters.filterId$contains, requestParameters.filterId$startsWith, requestParameters.filterId$nstartsWith, requestParameters.filterId$endsWith, requestParameters.filterId$nendsWith, requestParameters.filterId$in, requestParameters.filterId$nin, requestParameters.filterId$null, requestParameters.filterId$nnull, requestParameters.filterId$empty, requestParameters.filterId$nempty, requestParameters.filterId$like, requestParameters.filterName$eq, requestParameters.filterName$neq, requestParameters.filterName$contains, requestParameters.filterName$startsWith, requestParameters.filterName$nstartsWith, requestParameters.filterName$endsWith, requestParameters.filterName$nendsWith, requestParameters.filterName$in, requestParameters.filterName$nin, requestParameters.filterName$null, requestParameters.filterName$nnull, requestParameters.filterName$empty, requestParameters.filterName$nempty, requestParameters.filterName$like, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary authz: user.role,*,list
         * @param {RoleServiceApiRoleServiceListRoles2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceListRoles2(requestParameters: RoleServiceApiRoleServiceListRoles2Request, options?: AxiosRequestConfig): AxiosPromise<V1ListRolesResponse> {
            return localVarFp.roleServiceListRoles2(requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary authz: user.role,id,update
         * @param {RoleServiceApiRoleServiceUpdateRoleRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceUpdateRole(requestParameters: RoleServiceApiRoleServiceUpdateRoleRequest, options?: AxiosRequestConfig): AxiosPromise<V1Role> {
            return localVarFp.roleServiceUpdateRole(requestParameters.roleId, requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary authz: user.role,id,update
         * @param {RoleServiceApiRoleServiceUpdateRole2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceUpdateRole2(requestParameters: RoleServiceApiRoleServiceUpdateRole2Request, options?: AxiosRequestConfig): AxiosPromise<V1Role> {
            return localVarFp.roleServiceUpdateRole2(requestParameters.roleId, requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RoleServiceApiRoleServiceUpdateRolePermissionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roleServiceUpdateRolePermission(requestParameters: RoleServiceApiRoleServiceUpdateRolePermissionRequest, options?: AxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.roleServiceUpdateRolePermission(requestParameters.id, requestParameters.body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for roleServiceCreateRole operation in RoleServiceApi.
 * @export
 * @interface RoleServiceApiRoleServiceCreateRoleRequest
 */
export interface RoleServiceApiRoleServiceCreateRoleRequest {
    /**
     * 
     * @type {V1CreateRoleRequest}
     * @memberof RoleServiceApiRoleServiceCreateRole
     */
    readonly body: V1CreateRoleRequest
}

/**
 * Request parameters for roleServiceDeleteRole operation in RoleServiceApi.
 * @export
 * @interface RoleServiceApiRoleServiceDeleteRoleRequest
 */
export interface RoleServiceApiRoleServiceDeleteRoleRequest {
    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceDeleteRole
     */
    readonly id: string
}

/**
 * Request parameters for roleServiceGetRole operation in RoleServiceApi.
 * @export
 * @interface RoleServiceApiRoleServiceGetRoleRequest
 */
export interface RoleServiceApiRoleServiceGetRoleRequest {
    /**
     * id or name should be provided
     * @type {string}
     * @memberof RoleServiceApiRoleServiceGetRole
     */
    readonly id: string

    /**
     * id or name should be provided
     * @type {string}
     * @memberof RoleServiceApiRoleServiceGetRole
     */
    readonly name?: string
}

/**
 * Request parameters for roleServiceGetRolePermission operation in RoleServiceApi.
 * @export
 * @interface RoleServiceApiRoleServiceGetRolePermissionRequest
 */
export interface RoleServiceApiRoleServiceGetRolePermissionRequest {
    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceGetRolePermission
     */
    readonly id: string
}

/**
 * Request parameters for roleServiceListRoles operation in RoleServiceApi.
 * @export
 * @interface RoleServiceApiRoleServiceListRolesRequest
 */
export interface RoleServiceApiRoleServiceListRolesRequest {
    /**
     * 
     * @type {number}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly pageOffset?: number

    /**
     * 
     * @type {number}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly pageSize?: number

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly search?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly sort?: Array<string>

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly fields?: string

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterId$eq?: string

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterId$neq?: string

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterId$contains?: string

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterId$startsWith?: string

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterId$nstartsWith?: string

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterId$endsWith?: string

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterId$nendsWith?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterId$in?: Array<string>

    /**
     * 
     * @type {Array<string>}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterId$nin?: Array<string>

    /**
     * 
     * @type {boolean}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterId$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterId$nnull?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterId$empty?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterId$nempty?: boolean

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterId$like?: string

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterName$eq?: string

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterName$neq?: string

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterName$contains?: string

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterName$startsWith?: string

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterName$nstartsWith?: string

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterName$endsWith?: string

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterName$nendsWith?: string

    /**
     * 
     * @type {Array<string>}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterName$in?: Array<string>

    /**
     * 
     * @type {Array<string>}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterName$nin?: Array<string>

    /**
     * 
     * @type {boolean}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterName$null?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterName$nnull?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterName$empty?: boolean

    /**
     * 
     * @type {boolean}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterName$nempty?: boolean

    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceListRoles
     */
    readonly filterName$like?: string
}

/**
 * Request parameters for roleServiceListRoles2 operation in RoleServiceApi.
 * @export
 * @interface RoleServiceApiRoleServiceListRoles2Request
 */
export interface RoleServiceApiRoleServiceListRoles2Request {
    /**
     * 
     * @type {V1ListRolesRequest}
     * @memberof RoleServiceApiRoleServiceListRoles2
     */
    readonly body: V1ListRolesRequest
}

/**
 * Request parameters for roleServiceUpdateRole operation in RoleServiceApi.
 * @export
 * @interface RoleServiceApiRoleServiceUpdateRoleRequest
 */
export interface RoleServiceApiRoleServiceUpdateRoleRequest {
    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceUpdateRole
     */
    readonly roleId: string

    /**
     * 
     * @type {RoleServiceUpdateRoleRequest}
     * @memberof RoleServiceApiRoleServiceUpdateRole
     */
    readonly body: RoleServiceUpdateRoleRequest
}

/**
 * Request parameters for roleServiceUpdateRole2 operation in RoleServiceApi.
 * @export
 * @interface RoleServiceApiRoleServiceUpdateRole2Request
 */
export interface RoleServiceApiRoleServiceUpdateRole2Request {
    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceUpdateRole2
     */
    readonly roleId: string

    /**
     * 
     * @type {RoleServiceUpdateRoleRequest}
     * @memberof RoleServiceApiRoleServiceUpdateRole2
     */
    readonly body: RoleServiceUpdateRoleRequest
}

/**
 * Request parameters for roleServiceUpdateRolePermission operation in RoleServiceApi.
 * @export
 * @interface RoleServiceApiRoleServiceUpdateRolePermissionRequest
 */
export interface RoleServiceApiRoleServiceUpdateRolePermissionRequest {
    /**
     * 
     * @type {string}
     * @memberof RoleServiceApiRoleServiceUpdateRolePermission
     */
    readonly id: string

    /**
     * 
     * @type {RoleServiceUpdateRolePermissionRequest}
     * @memberof RoleServiceApiRoleServiceUpdateRolePermission
     */
    readonly body: RoleServiceUpdateRolePermissionRequest
}

/**
 * RoleServiceApi - object-oriented interface
 * @export
 * @class RoleServiceApi
 * @extends {BaseAPI}
 */
export class RoleServiceApi extends BaseAPI {
    /**
     * 
     * @summary authz: user.role,*,create
     * @param {RoleServiceApiRoleServiceCreateRoleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoleServiceApi
     */
    public roleServiceCreateRole(requestParameters: RoleServiceApiRoleServiceCreateRoleRequest, options?: AxiosRequestConfig) {
        return RoleServiceApiFp(this.configuration).roleServiceCreateRole(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary authz: user.role,id,delete
     * @param {RoleServiceApiRoleServiceDeleteRoleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoleServiceApi
     */
    public roleServiceDeleteRole(requestParameters: RoleServiceApiRoleServiceDeleteRoleRequest, options?: AxiosRequestConfig) {
        return RoleServiceApiFp(this.configuration).roleServiceDeleteRole(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary authz: user.role,id,get
     * @param {RoleServiceApiRoleServiceGetRoleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoleServiceApi
     */
    public roleServiceGetRole(requestParameters: RoleServiceApiRoleServiceGetRoleRequest, options?: AxiosRequestConfig) {
        return RoleServiceApiFp(this.configuration).roleServiceGetRole(requestParameters.id, requestParameters.name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RoleServiceApiRoleServiceGetRolePermissionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoleServiceApi
     */
    public roleServiceGetRolePermission(requestParameters: RoleServiceApiRoleServiceGetRolePermissionRequest, options?: AxiosRequestConfig) {
        return RoleServiceApiFp(this.configuration).roleServiceGetRolePermission(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary authz: user.role,*,list
     * @param {RoleServiceApiRoleServiceListRolesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoleServiceApi
     */
    public roleServiceListRoles(requestParameters: RoleServiceApiRoleServiceListRolesRequest = {}, options?: AxiosRequestConfig) {
        return RoleServiceApiFp(this.configuration).roleServiceListRoles(requestParameters.pageOffset, requestParameters.pageSize, requestParameters.search, requestParameters.sort, requestParameters.fields, requestParameters.filterId$eq, requestParameters.filterId$neq, requestParameters.filterId$contains, requestParameters.filterId$startsWith, requestParameters.filterId$nstartsWith, requestParameters.filterId$endsWith, requestParameters.filterId$nendsWith, requestParameters.filterId$in, requestParameters.filterId$nin, requestParameters.filterId$null, requestParameters.filterId$nnull, requestParameters.filterId$empty, requestParameters.filterId$nempty, requestParameters.filterId$like, requestParameters.filterName$eq, requestParameters.filterName$neq, requestParameters.filterName$contains, requestParameters.filterName$startsWith, requestParameters.filterName$nstartsWith, requestParameters.filterName$endsWith, requestParameters.filterName$nendsWith, requestParameters.filterName$in, requestParameters.filterName$nin, requestParameters.filterName$null, requestParameters.filterName$nnull, requestParameters.filterName$empty, requestParameters.filterName$nempty, requestParameters.filterName$like, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary authz: user.role,*,list
     * @param {RoleServiceApiRoleServiceListRoles2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoleServiceApi
     */
    public roleServiceListRoles2(requestParameters: RoleServiceApiRoleServiceListRoles2Request, options?: AxiosRequestConfig) {
        return RoleServiceApiFp(this.configuration).roleServiceListRoles2(requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary authz: user.role,id,update
     * @param {RoleServiceApiRoleServiceUpdateRoleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoleServiceApi
     */
    public roleServiceUpdateRole(requestParameters: RoleServiceApiRoleServiceUpdateRoleRequest, options?: AxiosRequestConfig) {
        return RoleServiceApiFp(this.configuration).roleServiceUpdateRole(requestParameters.roleId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary authz: user.role,id,update
     * @param {RoleServiceApiRoleServiceUpdateRole2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoleServiceApi
     */
    public roleServiceUpdateRole2(requestParameters: RoleServiceApiRoleServiceUpdateRole2Request, options?: AxiosRequestConfig) {
        return RoleServiceApiFp(this.configuration).roleServiceUpdateRole2(requestParameters.roleId, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RoleServiceApiRoleServiceUpdateRolePermissionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RoleServiceApi
     */
    public roleServiceUpdateRolePermission(requestParameters: RoleServiceApiRoleServiceUpdateRolePermissionRequest, options?: AxiosRequestConfig) {
        return RoleServiceApiFp(this.configuration).roleServiceUpdateRolePermission(requestParameters.id, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }
}

