/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ClientPatchOAuth2Client } from './client-patch-oauth2-client';

/**
 * 
 * @export
 * @interface ClientServicePatchOAuth2ClientRequest
 */
export interface ClientServicePatchOAuth2ClientRequest {
    /**
     * 
     * @type {Array<ClientPatchOAuth2Client>}
     * @memberof ClientServicePatchOAuth2ClientRequest
     */
    'client'?: Array<ClientPatchOAuth2Client>;
}

