/* tslint:disable */
/* eslint-disable */
/**
 * Saas Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ClientPatchOAuth2Client
 */
export interface ClientPatchOAuth2Client {
    /**
     * 
     * @type {string}
     * @memberof ClientPatchOAuth2Client
     */
    'from'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClientPatchOAuth2Client
     */
    'op'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientPatchOAuth2Client
     */
    'path'?: string;
    /**
     * 
     * @type {object}
     * @memberof ClientPatchOAuth2Client
     */
    'value'?: object;
}

