/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ClientListClientRequest
 */
export interface ClientListClientRequest {
    /**
     * 
     * @type {string}
     * @memberof ClientListClientRequest
     */
    'limit'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientListClientRequest
     */
    'offset'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientListClientRequest
     */
    'clientName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientListClientRequest
     */
    'owner'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientListClientRequest
     */
    'afterPageToken'?: string;
    /**
     * 
     * @type {string}
     * @memberof ClientListClientRequest
     */
    'beforePageToken'?: string;
}

