/* tslint:disable */
/* eslint-disable */
/**
 * Realtime Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface KeyJSONWebKey
 */
export interface KeyJSONWebKey {
    /**
     * 
     * @type {string}
     * @memberof KeyJSONWebKey
     */
    'alg': string;
    /**
     * 
     * @type {string}
     * @memberof KeyJSONWebKey
     */
    'crv'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KeyJSONWebKey
     */
    'd'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KeyJSONWebKey
     */
    'dp'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KeyJSONWebKey
     */
    'dq'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KeyJSONWebKey
     */
    'e'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KeyJSONWebKey
     */
    'k'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KeyJSONWebKey
     */
    'kid': string;
    /**
     * 
     * @type {string}
     * @memberof KeyJSONWebKey
     */
    'kty': string;
    /**
     * 
     * @type {string}
     * @memberof KeyJSONWebKey
     */
    'n'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KeyJSONWebKey
     */
    'p'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KeyJSONWebKey
     */
    'q'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KeyJSONWebKey
     */
    'qi'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KeyJSONWebKey
     */
    'use': string;
    /**
     * 
     * @type {string}
     * @memberof KeyJSONWebKey
     */
    'x'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof KeyJSONWebKey
     */
    'x5c'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof KeyJSONWebKey
     */
    'y'?: string | null;
}

