/* tslint:disable */
/* eslint-disable */
/**
 * Saas Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface KeyJsonWebKeySetGeneratorRequest
 */
export interface KeyJsonWebKeySetGeneratorRequest {
    /**
     * 
     * @type {string}
     * @memberof KeyJsonWebKeySetGeneratorRequest
     */
    'alg': string;
    /**
     * 
     * @type {string}
     * @memberof KeyJsonWebKeySetGeneratorRequest
     */
    'kid': string;
    /**
     * 
     * @type {string}
     * @memberof KeyJsonWebKeySetGeneratorRequest
     */
    'use': string;
}

