/* tslint:disable */
/* eslint-disable */
/**
 * Realtime Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LbsAddress
 */
export interface LbsAddress {
    /**
     * 
     * @type {string}
     * @memberof LbsAddress
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof LbsAddress
     */
    'region'?: string;
    /**
     * 
     * @type {string}
     * @memberof LbsAddress
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof LbsAddress
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof LbsAddress
     */
    'zipCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof LbsAddress
     */
    'line1'?: string;
    /**
     * 
     * @type {string}
     * @memberof LbsAddress
     */
    'line2'?: string;
    /**
     * 
     * @type {string}
     * @memberof LbsAddress
     */
    'line3'?: string;
    /**
     * 
     * @type {object}
     * @memberof LbsAddress
     */
    'geo'?: object;
}

