/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OperationBooleanFilterOperators
 */
export interface OperationBooleanFilterOperators {
    /**
     * 
     * @type {boolean}
     * @memberof OperationBooleanFilterOperators
     */
    '$eq'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof OperationBooleanFilterOperators
     */
    '$neq'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof OperationBooleanFilterOperators
     */
    '$null'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof OperationBooleanFilterOperators
     */
    '$nnull'?: boolean | null;
}

