/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { V1UpdatePriceParams } from './v1-update-price-params';

/**
 * 
 * @export
 * @interface PlanServiceUpdatePlanRequestPlan
 */
export interface PlanServiceUpdatePlanRequestPlan {
    /**
     * 
     * @type {string}
     * @memberof PlanServiceUpdatePlanRequestPlan
     */
    'displayName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PlanServiceUpdatePlanRequestPlan
     */
    'active'?: boolean;
    /**
     * 
     * @type {Array<V1UpdatePriceParams>}
     * @memberof PlanServiceUpdatePlanRequestPlan
     */
    'prices'?: Array<V1UpdatePriceParams>;
    /**
     * 
     * @type {number}
     * @memberof PlanServiceUpdatePlanRequestPlan
     */
    'sort'?: number;
}

