/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OrderServiceUpdateOrderRequestOrder } from './order-service-update-order-request-order';

/**
 * 
 * @export
 * @interface ProductCategoryServiceUpdateProductCategoryRequest
 */
export interface ProductCategoryServiceUpdateProductCategoryRequest {
    /**
     * 
     * @type {OrderServiceUpdateOrderRequestOrder}
     * @memberof ProductCategoryServiceUpdateProductCategoryRequest
     */
    'category'?: OrderServiceUpdateOrderRequestOrder;
    /**
     * 
     * @type {string}
     * @memberof ProductCategoryServiceUpdateProductCategoryRequest
     */
    'updateMask'?: string;
}

