/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { V1SubscriptionItemParams } from './v1-subscription-item-params';

/**
 * 
 * @export
 * @interface SubscriptionServiceUpdateSubscriptionRequestSubscription
 */
export interface SubscriptionServiceUpdateSubscriptionRequestSubscription {
    /**
     * 
     * @type {Array<V1SubscriptionItemParams>}
     * @memberof SubscriptionServiceUpdateSubscriptionRequestSubscription
     */
    'items'?: Array<V1SubscriptionItemParams>;
}

