/* tslint:disable */
/* eslint-disable */
/**
 * Realtime Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserServiceUpdateUserRequestUser } from './user-service-update-user-request-user';

/**
 * 
 * @export
 * @interface UserServiceUpdateUserRequest
 */
export interface UserServiceUpdateUserRequest {
    /**
     * 
     * @type {UserServiceUpdateUserRequestUser}
     * @memberof UserServiceUpdateUserRequest
     */
    'user'?: UserServiceUpdateUserRequestUser;
    /**
     * 
     * @type {string}
     * @memberof UserServiceUpdateUserRequest
     */
    'updateMask'?: string;
}

