/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { V1CreatePriceRequest } from './v1-create-price-request';

/**
 * 
 * @export
 * @interface V1CreatePlanRequest
 */
export interface V1CreatePlanRequest {
    /**
     * 
     * @type {string}
     * @memberof V1CreatePlanRequest
     */
    'key': string;
    /**
     * 
     * @type {string}
     * @memberof V1CreatePlanRequest
     */
    'displayName': string;
    /**
     * 
     * @type {Array<V1CreatePriceRequest>}
     * @memberof V1CreatePlanRequest
     */
    'prices'?: Array<V1CreatePriceRequest>;
}

