/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { V1OAuthClient } from './v1-oauth-client';

/**
 * 
 * @export
 * @interface V1GetConsentResponse
 */
export interface V1GetConsentResponse {
    /**
     * 
     * @type {string}
     * @memberof V1GetConsentResponse
     */
    'challenge': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1GetConsentResponse
     */
    'requestedScope'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V1GetConsentResponse
     */
    'userId'?: string;
    /**
     * 
     * @type {V1OAuthClient}
     * @memberof V1GetConsentResponse
     */
    'client'?: V1OAuthClient;
    /**
     * 
     * @type {string}
     * @memberof V1GetConsentResponse
     */
    'redirect'?: string;
}

