/* tslint:disable */
/* eslint-disable */
/**
 * Realtime Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1LoginPasswordlessRequest
 */
export interface V1LoginPasswordlessRequest {
    /**
     * 
     * @type {string}
     * @memberof V1LoginPasswordlessRequest
     */
    'phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1LoginPasswordlessRequest
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1LoginPasswordlessRequest
     */
    'token': string;
}

