/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Subscriptionv1Subscription } from './subscriptionv1-subscription';

/**
 * 
 * @export
 * @interface V1ListMySubscriptionReply
 */
export interface V1ListMySubscriptionReply {
    /**
     * 
     * @type {number}
     * @memberof V1ListMySubscriptionReply
     */
    'totalSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1ListMySubscriptionReply
     */
    'filterSize'?: number;
    /**
     * 
     * @type {Array<Subscriptionv1Subscription>}
     * @memberof V1ListMySubscriptionReply
     */
    'items'?: Array<Subscriptionv1Subscription>;
}

