/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { V1CategoryFilter } from './v1-category-filter';

/**
 * 
 * @export
 * @interface V1ListCategoryRequest
 */
export interface V1ListCategoryRequest {
    /**
     * 
     * @type {number}
     * @memberof V1ListCategoryRequest
     */
    'pageOffset'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1ListCategoryRequest
     */
    'pageSize'?: number;
    /**
     * 
     * @type {string}
     * @memberof V1ListCategoryRequest
     */
    'search'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1ListCategoryRequest
     */
    'sort'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V1ListCategoryRequest
     */
    'fields'?: string;
    /**
     * 
     * @type {V1CategoryFilter}
     * @memberof V1ListCategoryRequest
     */
    'filter'?: V1CategoryFilter;
}

