/* tslint:disable */
/* eslint-disable */
/**
 * Realtime Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { V1Notification } from './v1-notification';

/**
 * 
 * @export
 * @interface V1ListNotificationReply
 */
export interface V1ListNotificationReply {
    /**
     * 
     * @type {number}
     * @memberof V1ListNotificationReply
     */
    'totalSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1ListNotificationReply
     */
    'filterSize'?: number;
    /**
     * 
     * @type {Array<V1Notification>}
     * @memberof V1ListNotificationReply
     */
    'items'?: Array<V1Notification>;
    /**
     * 
     * @type {string}
     * @memberof V1ListNotificationReply
     */
    'nextAfterPageToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1ListNotificationReply
     */
    'nextBeforePageToken'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof V1ListNotificationReply
     */
    'unreadSize'?: number;
}

