/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { V1Order } from './v1-order';

/**
 * 
 * @export
 * @interface V1ListOrderReply
 */
export interface V1ListOrderReply {
    /**
     * 
     * @type {number}
     * @memberof V1ListOrderReply
     */
    'totalSize'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1ListOrderReply
     */
    'filterSize'?: number;
    /**
     * 
     * @type {Array<V1Order>}
     * @memberof V1ListOrderReply
     */
    'items'?: Array<V1Order>;
    /**
     * 
     * @type {string}
     * @memberof V1ListOrderReply
     */
    'nextAfterPageToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1ListOrderReply
     */
    'nextBeforePageToken'?: string | null;
}

