/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1Notification
 */
export interface V1Notification {
    /**
     * 
     * @type {string}
     * @memberof V1Notification
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Notification
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Notification
     */
    'group'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Notification
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Notification
     */
    'desc'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Notification
     */
    'image'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Notification
     */
    'link'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Notification
     */
    'source'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Notification
     */
    'userId'?: string;
    /**
     * 
     * @type {object}
     * @memberof V1Notification
     */
    'extra'?: object;
    /**
     * 
     * @type {number}
     * @memberof V1Notification
     */
    'level'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof V1Notification
     */
    'hasRead'?: boolean;
}

