/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1OrderProduct
 */
export interface V1OrderProduct {
    /**
     * 
     * @type {string}
     * @memberof V1OrderProduct
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1OrderProduct
     */
    'mainPic'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1OrderProduct
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1OrderProduct
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1OrderProduct
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1OrderProduct
     */
    'skuId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1OrderProduct
     */
    'skuTitle'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1OrderProduct
     */
    'priceId'?: string | null;
}

