/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { LbsAddress } from './lbs-address';
// May contain unused imports in some cases
// @ts-ignore
import { PricePricePb } from './price-price-pb';
// May contain unused imports in some cases
// @ts-ignore
import { V1OrderItem } from './v1-order-item';
// May contain unused imports in some cases
// @ts-ignore
import { V1OrderPaymentProvider } from './v1-order-payment-provider';
// May contain unused imports in some cases
// @ts-ignore
import { V1OrderPaymentProviderInfo } from './v1-order-payment-provider-info';

/**
 * 
 * @export
 * @interface V1Order
 */
export interface V1Order {
    /**
     * 
     * @type {string}
     * @memberof V1Order
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Order
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Order
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Order
     */
    'tenantId'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Order
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Order
     */
    'currencyCode'?: string;
    /**
     * 
     * @type {PricePricePb}
     * @memberof V1Order
     */
    'totalPrice'?: PricePricePb;
    /**
     * 
     * @type {PricePricePb}
     * @memberof V1Order
     */
    'totalPriceInclTax'?: PricePricePb;
    /**
     * 
     * @type {PricePricePb}
     * @memberof V1Order
     */
    'discount'?: PricePricePb;
    /**
     * 
     * @type {PricePricePb}
     * @memberof V1Order
     */
    'originalPrice'?: PricePricePb;
    /**
     * 
     * @type {PricePricePb}
     * @memberof V1Order
     */
    'paidPrice'?: PricePricePb;
    /**
     * 
     * @type {string}
     * @memberof V1Order
     */
    'paidTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Order
     */
    'payBefore'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Order
     */
    'payProvider'?: string;
    /**
     * 
     * @type {LbsAddress}
     * @memberof V1Order
     */
    'shippingAddr'?: LbsAddress;
    /**
     * 
     * @type {LbsAddress}
     * @memberof V1Order
     */
    'billingAddr'?: LbsAddress;
    /**
     * 
     * @type {string}
     * @memberof V1Order
     */
    'customerId'?: string;
    /**
     * 
     * @type {Array<V1OrderItem>}
     * @memberof V1Order
     */
    'items'?: Array<V1OrderItem>;
    /**
     * 
     * @type {V1OrderPaymentProviderInfo}
     * @memberof V1Order
     */
    'paymentProviderInfo'?: V1OrderPaymentProviderInfo;
    /**
     * 
     * @type {Array<V1OrderPaymentProvider>}
     * @memberof V1Order
     */
    'paymentProviders'?: Array<V1OrderPaymentProvider>;
}

