/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PricePricePb } from './price-price-pb';
// May contain unused imports in some cases
// @ts-ignore
import { V1PriceCurrencyOptionTier } from './v1-price-currency-option-tier';

/**
 * 
 * @export
 * @interface V1PriceCurrencyOption
 */
export interface V1PriceCurrencyOption {
    /**
     * 
     * @type {string}
     * @memberof V1PriceCurrencyOption
     */
    'currencyCode'?: string;
    /**
     * 
     * @type {PricePricePb}
     * @memberof V1PriceCurrencyOption
     */
    'default'?: PricePricePb;
    /**
     * 
     * @type {PricePricePb}
     * @memberof V1PriceCurrencyOption
     */
    'discounted'?: PricePricePb;
    /**
     * 
     * @type {string}
     * @memberof V1PriceCurrencyOption
     */
    'discountText'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1PriceCurrencyOption
     */
    'denyMoreDiscounts'?: boolean;
    /**
     * 
     * @type {Array<V1PriceCurrencyOptionTier>}
     * @memberof V1PriceCurrencyOption
     */
    'tiers'?: Array<V1PriceCurrencyOptionTier>;
}

