/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OperationBooleanFilterOperators } from './operation-boolean-filter-operators';
// May contain unused imports in some cases
// @ts-ignore
import { OperationStringFilterOperation } from './operation-string-filter-operation';

/**
 * 
 * @export
 * @interface V1PlanFilter
 */
export interface V1PlanFilter {
    /**
     * 
     * @type {OperationStringFilterOperation}
     * @memberof V1PlanFilter
     */
    'key'?: OperationStringFilterOperation;
    /**
     * 
     * @type {OperationStringFilterOperation}
     * @memberof V1PlanFilter
     */
    'displayName'?: OperationStringFilterOperation;
    /**
     * 
     * @type {OperationBooleanFilterOperators}
     * @memberof V1PlanFilter
     */
    'active'?: OperationBooleanFilterOperators;
}

