/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1SubscriptionItem
 */
export interface V1SubscriptionItem {
    /**
     * 
     * @type {string}
     * @memberof V1SubscriptionItem
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1SubscriptionItem
     */
    'priceId'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1SubscriptionItem
     */
    'productId'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1SubscriptionItem
     */
    'quantity'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1SubscriptionItem
     */
    'priceOwnerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1SubscriptionItem
     */
    'priceOwnerType'?: string;
    /**
     * 
     * @type {object}
     * @memberof V1SubscriptionItem
     */
    'bizPayload'?: object;
}

