/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { V1Price } from './v1-price';
// May contain unused imports in some cases
// @ts-ignore
import { V1Product } from './v1-product';
// May contain unused imports in some cases
// @ts-ignore
import { V1ProductSku } from './v1-product-sku';

/**
 * 
 * @export
 * @interface V1SubscriptionItem
 */
export interface V1SubscriptionItem {
    /**
     * 
     * @type {string}
     * @memberof V1SubscriptionItem
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1SubscriptionItem
     */
    'priceId'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1SubscriptionItem
     */
    'productId'?: string;
    /**
     * 
     * @type {number}
     * @memberof V1SubscriptionItem
     */
    'quantity'?: number;
    /**
     * 
     * @type {V1Price}
     * @memberof V1SubscriptionItem
     */
    'price'?: V1Price;
    /**
     * 
     * @type {V1Product}
     * @memberof V1SubscriptionItem
     */
    'product'?: V1Product;
    /**
     * 
     * @type {V1ProductSku}
     * @memberof V1SubscriptionItem
     */
    'productSku'?: V1ProductSku;
}

