/* tslint:disable */
/* eslint-disable */
/**
 * Realtime Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OperationStringFilterOperation } from './operation-string-filter-operation';

/**
 * 
 * @export
 * @interface V1TenantFilter
 */
export interface V1TenantFilter {
    /**
     * 
     * @type {OperationStringFilterOperation}
     * @memberof V1TenantFilter
     */
    'id'?: OperationStringFilterOperation;
    /**
     * 
     * @type {OperationStringFilterOperation}
     * @memberof V1TenantFilter
     */
    'name'?: OperationStringFilterOperation;
    /**
     * 
     * @type {OperationStringFilterOperation}
     * @memberof V1TenantFilter
     */
    'region'?: OperationStringFilterOperation;
}

