/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { V1Badge } from './v1-badge';
// May contain unused imports in some cases
// @ts-ignore
import { V1CampaignRule } from './v1-campaign-rule';
// May contain unused imports in some cases
// @ts-ignore
import { V1Keyword } from './v1-keyword';
// May contain unused imports in some cases
// @ts-ignore
import { V1PriceParams } from './v1-price-params';
// May contain unused imports in some cases
// @ts-ignore
import { V1ProductAttribute } from './v1-product-attribute';
// May contain unused imports in some cases
// @ts-ignore
import { V1ProductMedia } from './v1-product-media';
// May contain unused imports in some cases
// @ts-ignore
import { V1Stock } from './v1-stock';

/**
 * 
 * @export
 * @interface V1UpdateProduct
 */
export interface V1UpdateProduct {
    /**
     * 
     * @type {string}
     * @memberof V1UpdateProduct
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateProduct
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateProduct
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateProduct
     */
    'shortDesc'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateProduct
     */
    'desc'?: string;
    /**
     * 
     * @type {V1ProductMedia}
     * @memberof V1UpdateProduct
     */
    'mainPic'?: V1ProductMedia;
    /**
     * 
     * @type {Array<V1ProductMedia>}
     * @memberof V1UpdateProduct
     */
    'medias'?: Array<V1ProductMedia>;
    /**
     * 
     * @type {Array<V1Badge>}
     * @memberof V1UpdateProduct
     */
    'badges'?: Array<V1Badge>;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateProduct
     */
    'visibleFrom'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateProduct
     */
    'visibleTo'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1UpdateProduct
     */
    'isNew'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateProduct
     */
    'mainCategoryKey'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1UpdateProduct
     */
    'categoryKeys'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateProduct
     */
    'barcode'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateProduct
     */
    'model'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateProduct
     */
    'brandId'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof V1UpdateProduct
     */
    'isSaleable'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateProduct
     */
    'saleableFrom'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateProduct
     */
    'saleableTo'?: string;
    /**
     * 
     * @type {Array<V1Keyword>}
     * @memberof V1UpdateProduct
     */
    'keywords'?: Array<V1Keyword>;
    /**
     * 
     * @type {Array<V1PriceParams>}
     * @memberof V1UpdateProduct
     */
    'prices'?: Array<V1PriceParams>;
    /**
     * 
     * @type {boolean}
     * @memberof V1UpdateProduct
     */
    'isGiveaway'?: boolean;
    /**
     * 
     * @type {Array<V1ProductAttribute>}
     * @memberof V1UpdateProduct
     */
    'attributes'?: Array<V1ProductAttribute>;
    /**
     * 
     * @type {Array<V1CampaignRule>}
     * @memberof V1UpdateProduct
     */
    'campaignRules'?: Array<V1CampaignRule>;
    /**
     * 
     * @type {boolean}
     * @memberof V1UpdateProduct
     */
    'needShipping'?: boolean;
    /**
     * 
     * @type {Array<V1Stock>}
     * @memberof V1UpdateProduct
     */
    'stocks'?: Array<V1Stock>;
    /**
     * 
     * @type {object}
     * @memberof V1UpdateProduct
     */
    'content'?: object;
    /**
     * 
     * @type {boolean}
     * @memberof V1UpdateProduct
     */
    'active'?: boolean;
}

