/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { LbsAddress } from './lbs-address';

/**
 * 
 * @export
 * @interface V1UserAddress
 */
export interface V1UserAddress {
    /**
     * 
     * @type {string}
     * @memberof V1UserAddress
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UserAddress
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1UserAddress
     */
    'usage'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V1UserAddress
     */
    'prefer'?: boolean;
    /**
     * 
     * @type {LbsAddress}
     * @memberof V1UserAddress
     */
    'address'?: LbsAddress;
    /**
     * 
     * @type {object}
     * @memberof V1UserAddress
     */
    'metadata'?: object;
}

