/* tslint:disable */
/* eslint-disable */
/**
 * Realtime Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1UpdateRolePermissionAcl } from './v1-update-role-permission-acl';

/**
 * 
 * @export
 * @interface V1UpdateRole
 */
export interface V1UpdateRole {
    /**
     * 
     * @type {string}
     * @memberof V1UpdateRole
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof V1UpdateRole
     */
    'name': string;
    /**
     * 
     * @type {Array<V1UpdateRolePermissionAcl>}
     * @memberof V1UpdateRole
     */
    'acl'?: Array<V1UpdateRolePermissionAcl>;
}

