/* tslint:disable */
/* eslint-disable */
/**
 * order/api/order/v1/order.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BlobBlobFile } from './blob-blob-file';
// May contain unused imports in some cases
// @ts-ignore
import { V1Gender } from './v1-gender';
// May contain unused imports in some cases
// @ts-ignore
import { V1Role } from './v1-role';

/**
 * 
 * @export
 * @interface V1User
 */
export interface V1User {
    /**
     * 
     * @type {string}
     * @memberof V1User
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof V1User
     */
    'username'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1User
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1User
     */
    'phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1User
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof V1User
     */
    'birthday'?: string | null;
    /**
     * 
     * @type {V1Gender}
     * @memberof V1User
     */
    'gender'?: V1Gender;
    /**
     * 
     * @type {Array<V1Role>}
     * @memberof V1User
     */
    'roles'?: Array<V1Role>;
    /**
     * 
     * @type {BlobBlobFile}
     * @memberof V1User
     */
    'avatar'?: BlobBlobFile;
}



